# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'millennial-3'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: ''

menu:
- {name: 'Resources', url: 'resources'}
- {name: 'About',              url: 'about'}
#- {name: 'Interesting Facts',  url: 'facts'}
#- {name: 'Contact',            url: 'contact'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'youtube', link:   'https://www.youtube.com'}
- {icon: 'reddit', link:   'https://www.reddit.com'}
#- {icon: 'twitter', link:    'https://twitter.com/'}
#- {icon: 'facebook', link:   'https://www.facebook.com/'}
#- {icon: 'instagram', link:  'https://instagram.com/'}
#- {icon: 'envelope', link:   'mailto:'}
#- {icon: 'rss-square', link: 'feed.xml'}
# - {icon: 'rss-square', link: 'rss-feed.xml'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Feel free to share!'

related_posts: 'You may also enjoy...'

post_date_prefix: 'Written on'
